[window]
opacity = 0.98
[window.padding]
x = 1
y = 5

[cursor]
[cursor.style]
shape = "Beam"
blinking = "Always"

[font]
size = 11.5
[font.offset]
x = 0
y = 2
[font.normal]
    # family: UbuntuMono Nerd Font
    # family: DaddyTimeMono Nerd Font
    # family: Hack Nerd Font
    # family: JetBrainsMono Nerd Font
family = "CaskaydiaCove Nerd Font"
    # family: VictorMono Nerd Font
style = "Bold"

[font.bold]
family = "UbuntuMono Nerd Font Mono"
style = "Bold"
  
[font.italic]
family = "UbuntuMono Nerd Font Mono"
style = "Regular Italic"

[font.bold_italic]
family = "UbuntuMono Nerd Font Mono"
style = "Bold Italic"

[colors.primary]
background = '0x2a2a2a'
foreground = '0xabb2bf'
bright_foreground = '0xe6efff'
[colors.normal]
black = '0x1e2127'
red = '0xe06c75'
green = '0x98c379'
yellow = '0xd19a66'
blue = '0x61afef'
magenta = '0xc678dd'
cyan = '0x56b6c2'
white = '0x828791'
[colors.bright]
black = '0x5c6370'
red = '0xe06c75'
green = '0x98c379'
yellow = '0xd19a66'
blue = '0x61afef'
magenta = '0xc678dd'
cyan = '0x56b6c2'
white ='0xe6efff'
[colors.dim]
black = '0x1e2127'
red = '0xe06c75'
green ='0x98c379'
yellow = '0xd19a66'
blue = '0x61afef'
magenta = '0xc678dd'
cyan = '0x56b6c2'
white = '0x828791'
